#!/bin/bash
gcc -std=gnu99 -g -o otp_dec_d otp_dec_d.c
gcc -std=gnu99 -g -o otp_dec otp_dec.c
gcc -std=gnu99 -g -o otp_enc_d otp_enc_d.c
gcc -std=gnu99 -g -o otp_enc otp_enc.c
gcc -std=gnu99 -g -o keygen keygen.c